### ISSUE TITLE
PHP 5.6 above: Zip will be corrupted because it can't split a 64-bit integer to two 32-bit integers in int64_split function

### ISSUE THREAD

**Issue by hugohuynh** [barracudanetworks/ArchiveStream-php#24]
Hi,

With PHP 5.6 and above consider GMP resources are objects. So need to change int64_split function in Archive.php file to make it work with PHP 5.6+
function int64_split($value)
        {
            .....
            if (is_object($value)){ // php 5.6 above
                ....
                // $high = $this->gmp_convert(substr($hex, 0, 8), 16, 10);
                $high = gmp_strval(gmp_init(substr($hex, 0, 8), 16), 10);
                // $low  = $this->gmp_convert(substr($hex, 8, 8), 16, 10);
                $low = gmp_strval(gmp_init(substr($hex, 8, 8), 16), 10);
            }    
            .....
        }
I have tested on php 5.6 and php 7.0.4 and it works fine. If php 5.5 below can use the old code

Regards,
Trung.

**Comment by JohnMaguire** [comment]
Thanks @hugohuynh! I'll get around to adding these changes soon.

**Comment by iter-io** [comment]
@JohnMaguire, @hugohuynh  - I think my client is experiencing this error right now.  Any chance you want to fix it today?  I can send you funds via Paypal.

**Comment by iter-io** [comment]
@JohnMaguire  - The error message says "Unexpected end of archive" when using WinRAR on Windows.  On my Mac I get .cpgz files when I decompress.

**Comment by JohnMaguire** [comment]
Should be fixed in version 1.0.3.

**Comment by iter-io** [comment]
@JohnMaguire - Thank you for resolving this.  We have also experimented with this library:

https://github.com/maennchen/ZipStream-PHP

The interface is almost identical.  Maybe there's a way you guys can combine your efforts to maintain a solid library moving forward.

**Comment by JohnMaguire** [comment]
@iter-io Yes, both projects were forked from the same original project. While there are some similarities, there are also some distinct differences. For example, this library supports both tar and zip archives, as well as using GMP for large file support on 32-bit machines. I don't believe there are any plans to merge with another project currently. Thanks for the suggestion however. :)

**Comment by iter-io** [comment]
@JohnMaguire - True I overlooked that difference.  Good work on the code by the way.  I was mostly reading that as opposed to going by the docs.
