### ISSUE TITLE
Offline zip

### ISSUE THREAD

**Issue by hugohuynh** [barracudanetworks/ArchiveStream-php#26]
Hi  JohnMaguire,

Is it possible do offline zip. I mean the library can be configured to write to a zip file  Instead of streaming.

Thanks,
Trung.

**Comment by JohnMaguire** [comment]
There is no way to do it the way the library is currently written. If you wanted to modify the library, this function would just need to output to a file, instead of `echo`ing to the page: https://github.com/barracudanetworks/ArchiveStream-php/blob/master/src/Archive.php#L319-L329
