### ISSUE TITLE
Zip archives cannot be opened on OS X (Archive Utility, unzip)

### ISSUE THREAD

**Issue by mootari** [barracudanetworks/ArchiveStream-php#27]
When attempting to unzip a Zip archive on OS X via Finder, the system's archive utliity will only produce a .zip.cpgz file (apparently a temporary file created during decompression). Likewise, using unzip from the command line will fail with the warning "zipfile claims to be last disk of a multi-part archive".

The reason seems to be that unzip on OS X (including El Capitan) has been compiled without Zip64 support (unzip -v output below from OS X 10.9.5):
```
UnZip 5.52 of 28 February 2005, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.

Latest sources and executables are at ftp://ftp.info-zip.org/pub/infozip/ ;
see ftp://ftp.info-zip.org/pub/infozip/UnZip.html for other sites.

Compiled with gcc 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68) for Unix on Aug 24 2013.

UnZip special compilation options:
	COPYRIGHT_CLEAN (PKZIP 0.9x unreducing method not supported)
	SET_DIR_ATTRIB
	TIMESTAMP
	USE_EF_UT_TIME
	USE_UNSHRINK (PKZIP/Zip 1.x unshrinking method supported)
	USE_DEFLATE64 (PKZIP 4.x Deflate64(tm) supported)
	VMS_TEXT_CONV
	[decryption, version 2.9 of 05 May 2000]`
```

Would it be possible to make the use of Zip64 optional? I can't claim to be even remotely familiar with the Zip specs, and looking at ZipArchive I was unable to figure out the necessary steps.

**Comment by JohnMaguire** [comment]
@cisso I'm not certain we are interested in making Zip64 optional at this time. It would involve some reworking of the innards of the library. The function `Archive::instance_by_user_agent()` will create either a `ZipArchive` or `TarArchive` object dependent on whether you are on Windows (zip) or Linux/OSX (tar). Is there a reason you must get a zip file?

If you do indeed need a zip file, I'm fairly certain we'd be willing to accept a pull request to disable Zip64 support.

**Comment by cisso** [comment]
@JohnMaguire Thanks, serving tar archives is an option I hadn't even considered yet (we only considered pointing visitors to Keka).
Given the effort this feature would likely require, the fact that I don't have the skills to do it myself, and the listed alternatives, I'd be totally okay if this becomes Won't Fix.
