### ISSUE TITLE
Object of class GMP could not be converted to boolean

### ISSUE THREAD

**Issue by lapixo** [barracudanetworks/ArchiveStream-php#29]
Got an 
ErrorException: Object of class GMP could not be converted to boolean in vendor/barracudanetworks/archivestream-php/src/Archive.php:455

if i want to download a zip file. Tar works fine. 
Using PHP7.

**Comment by Cy4n1d3** [comment]
I second this.

Temporary workaround: comment out the corresponding block beginning on line 455.

**Comment by JohnMaguire** [comment]
Per the comment in the function `gmp_convert()`, we should really test for GMP existence earlier in the code (like the constructor) -- I'm also curious if the `use GMP;` statement that we've had since v1.0.0 is good enough to fail the script if GMP isn't compiled.
