### ISSUE TITLE
file corrupt

### ISSUE THREAD

**Issue by ifba** [barracudanetworks/ArchiveStream-php#30]
hi,
i have encrypted file,
while download multiple file, before add to zip i will decrypt the file. I have 3 file, i sucessfully created the zip, but only one file can be read other are corrupted
apache version 2.4
php 5.5
windows 10

```
foreach ($fileid as $key => $value) {
$file_info 		= $this->CI->pd_files_mdl->getFileById( $value );
			$zip->init_file_stream_transfer($file_info->name, $file_info->unencrypted_size);
$stream = fopen($userStorage.'/'.$file_info->path,'r');
			if ( $file_info->encrypted == 1 ){
				while (!feof($stream)) {
				    $buffer = fread($stream, 1024 * 1024);
				    $data = $aesCipher->decrypt($buffer);
	                            $zip->stream_file_part($data);
				  }	
				$zip->complete_file_stream();	
                        }
}

		$zip->finish();
```

**Comment by JohnMaguire** [comment]
@ifba How large is the resulting ZIP file? Possible dupe of #12.

**Comment by ifba** [comment]
HI, sorry for the late update,
the issue already solve, it not because of this library but my encryption library.

thank you

**Comment by JohnMaguire** [comment]
Thanks for the update!
