### ISSUE TITLE
Can you download from multiple pages simultaneously?

### ISSUE THREAD

**Issue by luku** [barracudanetworks/ArchiveStream-php#33]
I have problems with downloads of multiple files from same site.
When I try to open in browser 2 tabs (with pages from same site), that offer streaming download, I can download only from the first tab. When I switch to second tab and try to start new download there as well it dies. If I try to open any other page from same site in the seconds tab it dies as well, telling me the page is unreachable. It works just fine, if I try to visit the same page in another browser.
Repro on: Windows 10, Chrome, Edge

1. Is it not possible to download 2 files at the same time, using this lib, or is it some Windows only limitation?
2. Why is the whole site unreachable in the browser that is downloading? Is there something I'm missing?

**Comment by mootari** [comment]
My guess would be that your web server only uses a single process and as such can only serve a single request at a time.

**Comment by JohnMaguire** [comment]
This isn't a limitation imposed on the library. @mootari might have the right idea. Check your `php-fpm` configuration if you use it, or web server configuration otherwise. Wish I could help you more. Good luck.
