### ISSUE TITLE
Feature Request: add_file_from_path remote file

### ISSUE THREAD

**Issue by alimovz** [barracudanetworks/ArchiveStream-php#34]
Perhaps there is already a way to do this, but I am trying to zip up files located on a remote server. How can I do that without having to download them first. Example:
`$zip->add_file_from_path('videos/video.mp4', "https://dl.dropboxusercontent.com/1/view/jhdiuy2sdfs/somefiles/dd-4/45727_SampleVideo_1280x720_5mb.mp4", $file_opt);`

Would be great if it treated that remote path just like a local one.

**Comment by JohnMaguire** [comment]
This probably isn't going to happen, to be honest. You can either use a function like [`file_get_contents()`](https://secure.php.net/file_get_contents) to grab the entire file and send it to the archive, or even open a URL with [`fopen()`](https://secure.php.net/manual/en/function.fopen.php) and use the `stream_file_part()` method of adding data to the archive.

**Comment by alimovz** [comment]
Here is how I solved it.

`...
...
$fp = fsockopen("ssl://$host", 443, $errno, $errstr, 30);
	$out = "GET $path HTTP/1.1\r\n";
	$out .= "Host: $host\r\n";
	$out .= "Connection: Close\r\n\r\n";
	fwrite($fp, $out);
	
	//get the headers out
	$header = "";
	do{
		$header .= fgets($fp, 128);
	}while (strpos($header, "\r\n\r\n" ) === false);
	
	$zip->init_file_stream_transfer($folder."/".basename($path), $cont_length);
	
	while(!feof($fp)){
		$f = fgets($fp, 512);
		$zip->stream_file_part($f);
	}
	fclose($fp);
	
	$zip->complete_file_stream();
}

$zip->finish();
`

This way the user starts downloading immediately as opposed to waiting while file_get_contents gets the file to the server. So yes, your second suggestion is quite appropriate. Thanks.

**Comment by JohnMaguire** [comment]
Awesome, glad you got it working. 👍
