### ISSUE TITLE
Zip file is invalid in php version 5.5 and 5.6

### ISSUE THREAD

**Issue by ifba** [barracudanetworks/ArchiveStream-php#35]
HI,
I have some problem, when i create a zip file in server that have php version 5.5 and 5.6, the zip file is invalid. i already test in windows 10 and centos 7.2.
This issue never happen in php version 5.4.

ArchiveStream version 1.0.4

Thank you

**Comment by alimovz** [comment]
I use PHP 5.5.9-1ubuntu4.20. Works great for me.

**Comment by ifba** [comment]
found the problem 'Object of class GMP could not be converted to boolean in '.

thank you
