### ISSUE TITLE
Corrupt Zip archive on macOS

### ISSUE THREAD

**Issue by tillkruss** [barracudanetworks/ArchiveStream-php#38]
I get a corrupt archive when using this code on macOS Sierra using PHP 7.1:

```php
$zip = new \Barracuda\ArchiveStream\ZipArchive('foobar.zip');

$zip->add_file('hello.txt', 'This is the contents of hello.txt');

$zip->finish();
```

BetterZip reports the following:
```
Error: Can not open file as archive

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
```

**Comment by mootari** [comment]
That's a known issue, see https://github.com/barracudanetworks/ArchiveStream-php/issues/27

**Comment by tillkruss** [comment]
The problem is that we need a .zip file. Is there any way around this issue?

**Comment by mootari** [comment]
Unfortunately the only options I found back then were to either serve a tar archive for OS X clients or tell clients on OS X to use alternative archive tools like Keka to unpack the zip archive.

We went with the tar archive for OS X (but zip for other systems) as it opens without problems. The only downside to us was the less common extension that might irritate a client/visitor.

**Comment by tillkruss** [comment]
Okay, thanks. Chrome actually warns user about .tar files now.
